INSERT INTO ConservationStatus VALUES ('Canis latrans', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Canis lupus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Eptesicus fuscus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lasionycteris noctivagans', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Myotis keenii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Myotis leibii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Myotis lucifugus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Accipiter cooperii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Accipiter striatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Aquila chrysaetos', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Buteo lagopus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Buteo lineatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Circus cyaneus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Haliaeetus leucocephalus', 'In Recovery');
INSERT INTO ConservationStatus VALUES ('Cathartes aura', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pandion haliaetus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Aythya affinis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Selasphorus rufus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Fratercula arctica', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Charadrius melodus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Haematopus palliatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Chlidonias niger', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Larus atricilla', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Rynchops niger', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sterna hirundo', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Bartramia longicauda', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Numenius borealis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Numenius phaeopus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Coccyzus erythropthalmus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Falco columbarius', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Falco peregrinus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Gavia immer', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Rallus elegans', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Rallus longirostris', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Guiraca caerulea', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Piranga rubra', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Certhia americana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ammodramus savannarum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Melospiza lincolnii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pipilo chlorurus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Loxia curvirostra', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Progne subis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Riparia riparia', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Tachycineta bicolor', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lanius ludovicianus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Icteria virens', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Vermivora chrysoptera', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Vermivora ruficapilla', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Wilsonia pusilla', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Catharus bicknelli', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Contopus cooperi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Empidonax traillii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pyrocephalus rubinus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ardea herodias', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Botaurus lentiginosus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Nycticorax nycticorax', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pelecanus erythrorhynchos', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pelecanus occidentalis', 'In Recovery');
INSERT INTO ConservationStatus VALUES ('Dryocopus pileatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Picoides arcticus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Picoides pubescens', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Picoides tridactylus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sphyrapicus varius', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Asio flammeus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Asio otus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Phalacrocorax auritus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Diadophis punctatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Emydoidea blandingii', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Osmerus mordax', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Salmo salar', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Najas flexilis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Potamogeton confervoides', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sium suave', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Monotropa uniflora', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Amelanchier nantucketensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ovis canadensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Taxidea taxus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Bassariscus astutus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Nyctinomops macrotis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Antrozous pallidus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Euderma maculatum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Idionycteris phyllotis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Myotis californicus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Myotis evotis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Myotis thysanodes', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Myotis volans', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Myotis yumanensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pipistrellus hesperus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Gymnogyps californianus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Coccyzus americanus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Falco mexicanus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Gymnorhinus cyanocephalus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Amphispiza belli', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Spizella breweri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Oreoscoptes montanus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Oporornis tolmiei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sialia mexicana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Empidonax traillii extimus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Vireo vicinior', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plegadis chihi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sphyrapicus thyroideus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Aechmophorus occidentalis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Gambelia wislizenii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Catostomus latipinnis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Oreoxis trotteri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Erigeron kachinensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Perityle specuicola', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Mentzelia shultziorum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Primula specuicola', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus iselyi', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Dalea flavescens var. epica', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cycladenia humilis var. jonesii', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Sphaeralcea janeae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sphaeralcea psoraloides', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eragrostis pectinacea', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Mustela nigripes', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Myotis septentrionalis', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Myotis thysanodes pahasapensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cygnus buccinator', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Chordeiles acutipennis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Limosa fedoa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Numenius tahitiensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Grus americana', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Calcarius mccownii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Anthus spragueii', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Hybognathus argyritis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hybognathus placitus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Platygobio gracilis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Mirabilis nyctaginea', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eriogonum visheri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Myosurus minimus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Atrytone arogos arogos', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Speyeria idalia', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Leopardus pardalis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Nyctinomops femorosaccus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Leptonycteris nivalis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Myotis velifer', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sigmodon ochrognathus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Elanoides forficatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Elanus leucurus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Parabuteo unicinctus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Stellula calliope', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sterna antillarum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Patagioenas fasciata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Coturnicops noveboracensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Aimophila cassinii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Toxostoma crissale', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Dendroica chrysoparia', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Phainopepla nitens', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Campylorhynchus brunneicapillus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Myiarchus tyrannulus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Vireo atricapilla', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Egretta rufescens', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Micrathene whitneyi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Arizona elegans', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sonora semiannulata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Phrynosoma cornutum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Scaphiopus couchii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cycleptus elongatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Campostoma ornatum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hybognathus amarus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Notropis chihuahua', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Notropis jemezanus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cyprinodon eximius', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Gambusia gaigei', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Echinocereus chisoensis var. chisoensis', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Potamogeton clystocarpus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Agave glomeruliflora', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hexalectris nitida', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hexalectris revoluta', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Hexalectris warnockii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Brickellia brachyphylla var. terlinguensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Erigeron versicolor', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Perityle bisetosa var. scalaris', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cryptantha crassipes', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Phacelia pallida', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Streptanthus cutleri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Coryphantha chaffeyi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Coryphantha duncanii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Coryphantha ramillosa', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Echinocereus viridiflorus var. davisii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Echinomastus mariposensis', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Opuntia imbricata var. argentea', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Brongniartia minutifolia', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Polygala maravillasensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Quercus hinckleyi', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Justicia wrightii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Chamaesyce chaetocalyx var. triligulata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Chamaesyce golondrina', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Carex schweinitzii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Festuca ligulata', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Poa strictiramea', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Aquilegia longissima', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Convolvulus equitans', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Balaenoptera borealis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Balaenoptera physalus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Megaptera novaeangliae', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Physeter macrocephalus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Neotoma floridana smalli', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Dendrocygna bicolor', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Mycteria americana', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Patagioenas leucocephala', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Crocodylus acutus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Drymarchon corais couperi', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Crotalus adamanteus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Caretta caretta', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Chelonia mydas', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Eretmochelys imbricata', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Lepidochelys kempii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Dermochelys coriacea', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Pristis pectinata', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Harrisia aboriginum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Harrisia gracilis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Erithalis fruticosa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Argythamnia blodgettii', 'Proposed Threatened');
INSERT INTO ConservationStatus VALUES ('Byrsonima lucida', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Phyllanthus pentaphyllus var. floridanus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Jacquemontia curtissii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Acropora cervicornis', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Acropora palmata', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Orbicella franksi', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Sorex preblei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cypseloides niger', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Centrocercus minimus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Gila elegans', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Gila robusta', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cottus bairdii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lomatium concinnum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Iris missouriensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Tetraneuris torreyana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus anisus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus microcymbus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Castilleja sulphurea', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Penstemon retrorsus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Woodsia oregana ssp. cathcartiana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cynomys parvidens', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Cymopterus minimus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Erigeron sionis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cryptantha cinerea var. arenicola', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cryptantha ochroleuca', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Silene petersonii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eriogonum aretioides', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Mentzelia argillosa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus limnocharis var. tabulaeus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Penstemon bracteatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Strix occidentalis lucida', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Xyrauchen texanus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Gila cypha', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Ptychocheilus lucius', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Pediomelum aromaticum var. tuhyi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Carex specuicola', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Chaetura vauxi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sauromalus ater', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Snyderichthys copei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Erigeron maguirei', 'In Recovery');
INSERT INTO ConservationStatus VALUES ('Thelesperma subnudum var. alpinum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Townsendia aprica', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Cryptantha rollinsii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Schoenocrambe barnebyi', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Pediocactus despainii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Pediocactus winkleri', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Sclerocactus wrightiae', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Astragalus subcinereus var. basalticus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Juglans cinerea', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Panthera onca', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Tympanuchus pallidicinctus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Sistrurus catenatus', 'Proposed Threatened');
INSERT INTO ConservationStatus VALUES ('Chaetopappa hersheyi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hieracium fendleri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Packera hartiana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Streptanthus sparsiflorus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Echinocereus viridiflorus var. cylindricus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Dalea foliosa', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Dichanthelium acuminatum var. acuminatum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Enhydra lutris nereis', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Arctocephalus townsendi', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Eumetopias jubatus', 'In Recovery');
INSERT INTO ConservationStatus VALUES ('Eubalaena glacialis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Balaenoptera musculus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Eschrichtius robustus', 'In Recovery');
INSERT INTO ConservationStatus VALUES ('Physeter catodon', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Plecotus townsendii townsendii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Brachyramphus marmoratus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Fratercula cirrhata', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Ptychoramphus aleuticus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Synthliboramphus hypoleucus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Haematopus bachmani', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sterna elegans', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pica nuttalli', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Carduelis lawrencei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Agelaius tricolor', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Diomedea albatrus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Xantusia riversiana', 'In Recovery');
INSERT INTO ConservationStatus VALUES ('Caretta caretta', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Chelonia mydas', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Batrachoseps nigriventris', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Batrachoseps pacificus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eucyclogobius newberryi', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Eriophyllum nevinii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lasthenia glabrata ssp. coulteri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Layia platyglossa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Malacothrix indecora', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Malacothrix squalida', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Phacelia distans', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Phacelia insularis var. insularis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Arabis hoffmannii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Erysimum ammophilum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lepidium virginicum var. robinsonii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sibara filifolia', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Thysanocarpus conchuliferus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Aphanisma blitoides', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Atriplex coulteri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Atriplex pacifica', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Atriplex serenana var. davidsonii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Suaeda taxifolia', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eriogonum giganteum var. compactum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eriogonum grande var. rubescens', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Arctostaphylos confertiflora', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Gilia tenuiflora ssp. hoffmannii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Astragalus traskiae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lotus argophyllus var. niveus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lotus dendroideus var. traskiae', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Quercus dumosa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Quercus engelmannii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Galium buxifolium', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Erodium macrophyllum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Castilleja mollis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Orobanche parishii ssp. brachyloba', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Mimulus brandegeei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Gambelia speciosa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Calochortus catalinae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lilium humboldtii ssp. ocellatum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Euphorbia misera', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Helianthemum greenei', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Cupressus macrocarpa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pinus radiata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pinus torreyana var. insularis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hordeum intercedens', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Berberis pinnata ssp. insularis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Dendromecon harfordii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Platystemon californicus var. ciliatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lyonothamnus floribundus ssp. aspleniifolius', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Dudleya candelabrum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Dudleya nesiotica', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Dudleya traskiae', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Ribes thacherianum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Jepsonia malvifolia', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Calystegia macrostegia ssp. amplissima', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Haliotis cracherodii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Haliotis sorenseni', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Myotis austroriparius', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Aimophila aestivalis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Vermivora bachmanii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Campephilus principalis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Picoides borealis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Heterodon simus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Thamnophis sauritus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Pseudemys concinna', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Acipenser brevirostrum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Macbridea caroliniana', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Porella pinnata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eurytides marcellus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Macromia taeniolata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Martes pennanti', 'Proposed Threatened');
INSERT INTO ConservationStatus VALUES ('Ursus arctos horribilis', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Falco peregrinus anatum', 'In Recovery');
INSERT INTO ConservationStatus VALUES ('Strix occidentalis caurina', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Sceloporus graciosus graciosus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Bufo boreas', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ascaphus truei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Rana boylii', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Rana cascadae', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Rana pretiosa', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Ambystoma gracile', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Dicamptodon tenebrosus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Taricha granulosa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Oncorhynchus kisutch', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Salvelinus confluentus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Liatris provincialis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cryptantha sobolifera', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Arabis suffrutescens var. horizontalis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eriogonum ovalifolium ssp. vineum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Eriogonum ovalifolium var. vineum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Collomia mazama', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus applegatei', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Penstemon peckii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Botrychium pumicola', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pinus albicaulis', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Apatania tavala', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Myotis sodalis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Regina septemvittata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Acipenser fulvescens', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ammocrypta pellucida', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Stizostedion vitreum glaucum', 'Extinct');
INSERT INTO ConservationStatus VALUES ('Tsuga caroliniana', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Malaxis brachypoda', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Taraxacum carneocoloratum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Smelowskia pyriformis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Botrychium ascendens', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Carex lenticularis var. dolia', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Dicranoweisia crispula', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Gulo gulo luteus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Macrotus californicus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lasiurus blossevillii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Microtus californicus vallicola', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Microtus montanus nevadensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Chaetodipus fallax', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Perognathus inornatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Laterallus jamaicensis', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Amphispiza belli belli', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Toxostoma lecontei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sitta carolinensis aculeata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ixobrychus exilis hesperis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Melanerpes uropygialis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Athene cunicularia hypugaea', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Elgaria panamintina', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Thamnophis hammondii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Heloderma suspectum cinctum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Dipsosaurus dorsalis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Uma notata', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Crotalus cerastes', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Crotalus mitchellii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Gopherus agassizii', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Rana draytonii', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Batrachoseps aridus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Batrachoseps campi', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Batrachoseps relictus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Batrachoseps simatus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Batrachoseps wrighti', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Hydromantes platycephalus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hydromantes shastae', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Rhinichthys osculus nevadensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyprinodon diabolis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cordylanthus maritimus var. maritimus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Oenothera avita eurekensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cymopterus ripleyi var. saniculoides', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Agave shawii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Spiranthes infernalis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cirsium mohavense', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Enceliopsis covillei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Enceliopsis nudicaulis var. corrugata', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Erigeron parishii', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Pentachaeta lyonii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Perityle inyoensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Perityle villosa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cryptantha roosiorum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Phacelia amabilis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Phacelia beatleyae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Phacelia monoensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Phacelia parishii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Caulostramina jaegeri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Nitrophila mohavensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Suaeda nigra', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Chorizanthe orcuttiana', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Chorizanthe parryi var. fernandina', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Dedeckera eurekensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eriogonum bifurcatum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eriogonum eremicola', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eriogonum intrafractum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eriogonum microthecum var. panamintense', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eriogonum tiehmii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Mentzelia leucophylla', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Petalonyx thurberi ssp. gilmanii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Phlox dolichantha', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus brauntonii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Astragalus funereus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus gilmanii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus lentiginosus var. piscinensis', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Astragalus mohavensis var. hemigyrus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus phoenix', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Astragalus tener var. titi', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Lupinus magnificus var. magnificus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pediomelum castoreum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Asclepias eastwoodiana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Frasera pahutensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Galium hilendiae ssp. kingstonense', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Castilleja applegatei ssp. martinii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cordylanthus tecopensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Holmgrenanthe petrophila', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Penstemon arenarius', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Penstemon fruticiformis var. amargosae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Penstemon lemhiensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Penstemon pahutensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Penstemon wardii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Calochortus excavatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Calochortus striatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sphaeralcea rusbyi var. eremicola', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Camissonia megalantha', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Swallenia alexandrae', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Arctomecon humilis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Arctomecon merriamii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Dudleya abramsii ssp. parva', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Dudleya cymosa ssp. marcescens', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Dudleya cymosa ssp. ovatifolia', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Dudleya cymosa var. ovatifolia', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Dudleya saxosa ssp. saxosa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Dudleya saxosa var. saxosa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Dudleya verityi', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Oryctes nevadensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Helisoma newberryi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Assiminea infima', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pyrgulopsis aardahli', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pyrgulopsis avernalis', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Pyrgulopsis bruneauensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Pyrgulopsis crystalis', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Pyrgulopsis erythropoma', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Pyrgulopsis fairbanksensis', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Pyrgulopsis isolata', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Pyrgulopsis merriami', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Pyrgulopsis nanus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Pyrgulopsis owensensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pyrgulopsis perturbata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pyrgulopsis pisteri', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Pyrgulopsis wongi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Tryonia angulata', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Tryonia clathrata', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Tryonia elata', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Tryonia ericae', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Tryonia imitator', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Tryonia margae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Tryonia robusta', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Tryonia rowlandsi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Tryonia variegata', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Cicindela arenicola', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Miloderes nelsoni', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Miloderes rulieni', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Stygoparnus comalensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Heterelmis comalensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Heterelmis stephani', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Microcylloepus formicoideus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Microcylloepus similis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Glaresis arenata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Brychius hungerfordi', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Polyphylla anteronivea', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Polyphylla avittata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Polyphylla barbata', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Polyphylla erratica', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Polyphylla nubila', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Belostoma saratogae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ambrysus amargosus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Polites sabuleti albamontana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ischnura', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Megalagrion nesiotes', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Megalagrion pacificum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Megalagrion xanthomelas', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Somatochlora hineana', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Texosporium sancti-jacobi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Trichechus manatus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Mycetophyllia ferox', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Puma concolor coryi', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Neofiber alleni', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Peromyscus gossypinus allapaticola', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Rostrhamus sociabilis plumbeus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Ammodramus maritimus mirabilis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Dendroica kirtlandii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Crocodylus acutus', 'Resident');
INSERT INTO ConservationStatus VALUES ('Ophisaurus compressus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Caretta caretta', 'Breeder');
INSERT INTO ConservationStatus VALUES ('Pseudemys nelsoni', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Gopherus polyphemus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Encyclia cochleata var. triandra', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Mesadenus polyanthus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Spiranthes lanceolata var. paludicola', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Chromolaena frustrata', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Melanthera parvifolia', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sideroxylon reclinatum ssp. austrofloridense', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Aeschynomene pratensis', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Chamaecrista lineata var. keyensis', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Dalea carthagenensis var. floridana', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Galactia pinetorum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Galactia smallii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Trichomanes punctatum ssp. floridanum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Elytraria caroliniensis var. angustifolia', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Glandularia maritima', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Chamaesyce deltoidea ssp. pinetorum', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Chamaesyce garberi', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Tragia saxicola', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Linum arenicola', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Linum carteri var. smallii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Digitaria pauciflora', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Eriochloa michauxii var. simpsonii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Tripsacum floridanum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Symphyotrichum yukonense', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Mertensia drummondii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Canis lupus', 'In Recovery');
INSERT INTO ConservationStatus VALUES ('Rana luteiventris', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Erigeron lackschewitzii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Botrychium crenulatum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Botrychium paradoxum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Papaver pygmaeum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Campylium cardotii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lednia tumana', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Eschrichtius robustus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Sorex alaskanus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Acipenser medirostris', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Lampetra tridentata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Prosopium coulterii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Aphelocoma coerulescens', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Masticophis flagellum piceus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Gambelia wislizenii wislizenii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Relictus solitarius', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Oncorhynchus clarkii henshawi', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Cryptantha welshii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Draba oreibata var. serpentina', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Silene nachlingerae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eriogonum holmgrenii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Jamesia tetrapetala', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Primula maguirei', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Primula nevadensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus lentiginosus var. scorpionis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Penstemon concinnus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sphaeralcea caespitosa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ivesia shockleyi var. ostleri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Potentilla cottamii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Oreohelix nevadensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eumops perotis californicus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Choeronycteris mexicana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Rallus longirostris yumanensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Ammodramus savannarum perpallidus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Empidonax traillii brewsteri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Colaptes chrysoides', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lampropeltis getula californiae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Rhinocheilus lecontei lecontei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Thamnophis rufipunctatus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Trimorphodon biscutatus lambda', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lithobates onca', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Spea hammondii', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Phacelia serrata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Talinum validulum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Anulocaulis leiosolenus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ipomopsis polyantha', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Astragalus cremnophylax var. cremnophylax', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Camissonia specuicola ssp. hesperia', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Arctomecon californica', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Rosa stellata ssp. abyssa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Oxyloma haydeni kanabensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cervus elaphus', 'Migratory');
INSERT INTO ConservationStatus VALUES ('Mustela erminea', 'Migratory');
INSERT INTO ConservationStatus VALUES ('Peromyscus maniculatus', 'Breeder');
INSERT INTO ConservationStatus VALUES ('Accipiter gentilis', 'Breeder');
INSERT INTO ConservationStatus VALUES ('Anas acuta', 'Resident');
INSERT INTO ConservationStatus VALUES ('Phalaenoptilus nuttallii', 'Breeder');
INSERT INTO ConservationStatus VALUES ('Falco columbarius', 'Resident');
INSERT INTO ConservationStatus VALUES ('Psaltriparus minimus', 'Breeder');
INSERT INTO ConservationStatus VALUES ('Corvus brachyrhynchos', 'Resident');
INSERT INTO ConservationStatus VALUES ('Dumetella carolinensis', 'Resident');
INSERT INTO ConservationStatus VALUES ('Turdus migratorius', 'Breeder');
INSERT INTO ConservationStatus VALUES ('Salvelinus fontinalis', 'Breeder');
INSERT INTO ConservationStatus VALUES ('Draba smithii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cleome multicaulis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Canis rufus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Myotis grisescens', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Glaucomys sabrinus coloratus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Thryomanes bewickii altus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pituophis melanoleucus melanoleucus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cryptobranchus alleganiensis alleganiensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Aneides aeneus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Desmognathus aeneus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Desmognathus wrighti', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Erimonax monachus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Hemitremia flammea', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Notropis ariommus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Etheostoma percnurum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Percina burtoni', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Percina macrocephala', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Percina squamata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Noturus baileyi', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Noturus flavipinnis', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Potamogeton tennesseensis', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Tofieldia glabra', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Zizia trifoliata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Isotria medeoloides', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Parthenium integrifolium', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Rugelia nudicaulis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cardamine clematitis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Silene ovata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Parnassia grandifolia', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Shortia galacifolia', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Monotropsis odorata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Vaccinium hirsutum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lysimachia fraseri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lilium grayi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Trillium pusillum var. pusillum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Euphorbia purpurea', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Abies fraseri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Carex communis var. amplisquama', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Calamagrostis cainii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Glyceria nubigena', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Poa paludigena', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Delphinium exaltatum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Geum radiatum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Spiraea virginiana', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Buckleya distichophylla', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Saxifraga caroliniana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plagiomnium carolinianum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Megaceros aenigmaticus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Fissidens appalachensis', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Leptohymenium sharpii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Bazzania nudicaulis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lophocolea appalachiana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plagiochila caduciloba', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Plagiochila sharpii', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Plagiochila sullivantii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plagiochila virginica var. caroliniana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sphenolobopsis pearsonii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lejeunea blomquistii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Tortula ammonsiana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Leptoxis praerosa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Patera clarki nantahala', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Vertigo ovata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Microhexura montivaga', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Eulonchus marialiciae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Serratella serrata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Bombus affinis', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Euchlaena milnei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Semiothisa fraserata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hepialus sciophanes', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Phyciodes batesii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Speyeria diana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Macromia margarita', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Allocapnia fumosa', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Megaleuctra williamsae', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Cheumatopsyche helma', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Gymnoderma lineare', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Phaeophyscia leana', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Lesquerella carinata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lesquerella paysonii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus paysonii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Mimulus patulus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Achnatherum contractum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ranunculus acriformis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Coryphantha sneedii var. sneedii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Nolina arenicola', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lepidospartum burgessii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Symphoricarpos guadalupensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Monachus schauinslandi', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Lasiurus cinereus semotus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Anas wyvilliana', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Branta sandvicensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Palmeria dolei', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Pseudonestor xanthophrys', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Oceanodroma castro', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Pterodroma sandwichensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Puffinus auricularis newelli', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Asio flammeus sandwichensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lentipes concolor', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sanicula sandwicensis', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Platanthera holochila', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Argyroxiphium sandwicense ssp. macrocephalum', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Bidens campylotheca ssp. pentamera', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Bidens campylotheca ssp. waihoiensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Bidens micrantha ssp. kalealaha', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Clermontia lindseyana', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Clermontia oblongifolia ssp. mauiensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Clermontia peleana', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyanea asplenifolia', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyanea copelandii ssp. haleakalaensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyanea glabra', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyanea hamatiflora ssp. hamatiflora', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyanea horrida', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyanea kunthiana', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyanea longissima', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cyanea mauiensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyanea solanacea', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Schiedea haleakalensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Phytolacca sandwicensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sicyos cucumerinus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Gardenia remyi', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Geranium arboreum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Geranium hanaense', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Geranium multiflorum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyrtandra ferripilosa', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyrtandra filipes', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Phyllostegia bracteata', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Phyllostegia brevidens', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Phyllostegia haliakalae', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Stenogyne haliakalae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Huperzia mannii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Huperzia stemmermanniae', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Wikstroemia villosa', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyperus neokunthianus', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Joinvillea ascendens ssp. ascendens', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Calamagrostis expansa', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Cenchrus agrimonioides', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Ischaemum byrone', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Asplenium schizophyllum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ctenitis squamigera', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Ranunculus hawaiensis', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Ranunculus mauiensis', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Rubus macraei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Korthalsella degeneri', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Melicope balloui', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Melicope haleakalae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Melicope ovalis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Nothocestrum latifolium', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Solanum incompletum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Partulina anceyana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Partulina dolei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Partulina nivea', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Partulina porcellana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Perdicella carinella', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Proterhinus deceptor', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Proterhinus epitretus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Proterhinus fuscicolor', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Proterhinus nivicola', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pseudobroscus lentus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plagithmysus dubautianus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plagithmysus forbesii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plagithmysus koae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plagithmysus swezeyanus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Nesosydne bridwelli', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ithamar hawaiiensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hylaeus coniceps', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hylaeus difficilis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hylaeus unicus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hylaeus volatilis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ectemnius haleakalae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Thyrocopa apatela', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Micromus cookeorum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Micromus haleakalae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Micromus lobipennis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Buteo solitarius', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Corvus hawaiiensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Psittirostra psittacea', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Spermolepis hawaiiensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Pittosporum hawaiiense', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Pritchardia lanigera', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Pritchardia maideniana', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Argyroxiphium kauense', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Argyroxiphium sandwicense ssp. sandwicense', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyanea platyphylla', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyanea shipmanii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyanea stictophylla', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyanea tritomantha', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Capparis sandwichiana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Schiedea diffusa ssp. macraei', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Silene hawaiiensis', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Portulaca sclerocarpa', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Portulaca villosa', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Sicyos albus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Sicyos macrophyllus', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Eurya sandwicensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sesbania tomentosa', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Ochrosia haleakalae', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Ochrosia kilaueaensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Bobea timonioides', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cyrtandra giffardii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyrtandra tintinnabula', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Haplostachys haplostachya', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Phyllostegia floribunda', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Phyllostegia racemosa', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Phyllostegia stachyoides', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Phyllostegia velutina', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Plantago hawaiensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Hibiscadelphus giffardianus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Hibiscadelphus hualalaiensis', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Kokia drynarioides', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Fimbristylis hawaiiensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Adenophorus periens', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Neraudia ovata', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Exocarpos gaudichaudii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Exocarpos menziesii', 'Proposed Endangered');
INSERT INTO ConservationStatus VALUES ('Melicope zahlbruckneri', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Zanthoxylum hawaiiense', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Nothocestrum breviflorum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Metabetaeus lohena', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Proterhinus affinis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Proterhinus deceptor major', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Proterhinus desquamatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Proterhinus eurhynchus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Proterhinus ferrugineus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Proterhinus peles', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Proterhinus rufescens', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Proterhinus similis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Proterhinus tarsalis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Proterhinus vulcanus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plagithmysus claviger', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plagithmysus decorus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plagithmysus platydesmae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plagithmysus sulphurescens', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Deinocossonus nesiotes', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Nesotocus munroi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eopenthes cognatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Drosophila digressa', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Drosophila heteroneura', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Drosophila mulli', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Nesosydne cyrtandricola', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Metrarga obscura', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cavaticovelia aaa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Coleotichus blackburniae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Oechalia grisea', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Nesidiolestes ana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hylaeus crabronoides', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hylaeus filicum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hylaeus flavipes', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hylaeus hula', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hylaeus laetus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hylaeus pubescens', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hylaeus simplex', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hylaeus specularis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hylaeus sphecodoides', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Deinomimesa hawaiiensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ectemnius curtipes', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ectemnius fulvicrus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ectemnius rubrocaudatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Agrotis microreas', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Omiodes anastrepta', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Omiodes anastreptoides', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Omiodes asaphombra', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Omiodes fullawayi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Omiodes giffardi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Omiodes iridias', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Omiodes pritchardii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Thaumatogryllus cavicola', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Caconemobius varius', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lanius ludovicianus migrans', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Desmognathus brimleyorum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Etheostoma pallididorsum', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Noturus lachneri', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Ptilimnium nodosum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cypripedium kentuckiense', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Helianthus occidentalis ssp. plantagineus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Amorpha ouachitensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hypericum adpressum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Carex latebracteata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Dichanthelium aciculare ssp. aciculare', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Dichanthelium acuminatum ssp. acuminatum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Coregonus kiyi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Coregonus zenithicus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Arnica lonchophylla', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ovis canadensis nelsoni', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Hulsea callicarpha', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hulsea vestita ssp. callicarpha', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Phacelia nashiana', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Coryphantha vivipara var. alversonii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Gilia maculata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Gilia tenuiflora ssp. arenaria', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Linanthus concinnus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus lentiginosus var. coachellae', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Astragalus tricarinatus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Quercus berberidifolia', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Monardella robisonii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Penstemon stephensii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Calochortus palmeri var. palmeri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Chamaesyce platysperma', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ditaxis serrata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eumetopias jubatus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Delphinapterus leucas', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Polysticta stelleri', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Phoebastria albatrus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Primula tschuktschorum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Rissa brevirostris', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Rumex krausei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Aplodontia rufa californica', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Branta canadensis leucopareia', 'In Recovery');
INSERT INTO ConservationStatus VALUES ('Strix occidentalis occidentalis', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Catostomus microps', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Oncorhynchus mykiss', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Oncorhynchus tshawytscha', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cottus asperrimus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Brodiaea coronaria ssp. rosea', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eriophyllum lanatum var. hallii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Arabis breweri var. pecuniaria', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Erysimum capitatum ssp. angustatum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Eriogonum nudum var. murinum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Anacolia menziesii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Claopodium whippleanum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cryptobranchus alleganiensis', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Etheostoma tippecanoe', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Amblyopsis spelaea', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Typhlichthys subterraneus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Helianthus eggertii', 'In Recovery');
INSERT INTO ConservationStatus VALUES ('Rudbeckia triloba var. pinnatiloba', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Aureolaria patula', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Palaemonias ganteri', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cumberlandia monodonta', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Cyprogenia stegaria', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Epioblasma torulosa rangiana', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Epioblasma triquetra', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Fusconaia subrotunda', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Lampsilis abrupta', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Obovaria retusa', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Obovaria subrotunda', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Plethobasus cyphyus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Pleurobema plenum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Pleurobema pyramidatum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pleurobema rubrum', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Villosa ortmanni', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Elanus caeruleus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sisyrinchium pallidum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cypripedium fasciculatum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Spiranthes diluvialis', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Hackelia gracilenta', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pediocactus knowltonii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Sclerocactus mesae-verdae', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Astragalus cronquistii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus deterior', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus humillimus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Astragalus schmolliae', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Penstemon parviflorus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lagopus leucura rainierensis', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Plethodon vandykei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plethodon vehiculum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Rhyacotriton cascadae', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Oncorhynchus tshawytscha', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Castilleja cryptantha', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Penstemon barrettiae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Nebria paradisi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Luina serpentina', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hackelia venusta', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Silene seelyi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Botrychium pedunculosum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cimicifuga elata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Bembidion stillaguamish', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Oncorhynchus keta', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Oncorhynchus nerka', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Arenaria paludicola', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Montia howellii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Abronia umbellata ssp. breviflora', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Dodecatheon austrofrigidum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus cottonii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Calamagrostis crassiglumis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pediocactus peeblesianus var. peeblesianus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Sclerocactus papyracanthus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus brandegeei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus xiphoides', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sylvilagus bachmani', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ammospermophilus nelsoni', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Archoplites interruptus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pentachaeta exilis ssp. aeolica', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plagiobothrys uncinatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Juglans californica var. hindsii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Callitriche marginata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Delphinium californicum ssp. interius', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Calystegia collina ssp. venusta', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Optioservus canus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Arborimus albipes', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Brachyramphus marmoratus marmoratus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Charadrius alexandrinus nivosus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Falco peregrinus tundrius', 'In Recovery');
INSERT INTO ConservationStatus VALUES ('Lepidochelys olivacea', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Rana aurora aurora', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plethodon dunni', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plethodon elongatus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Chasmistes brevirostris', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Deltistes luxatus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Hypomesus transpacificus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Sanicula arctopoides', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sanicula tracyi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Tauschia howellii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Hastingsia bracteosa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Erigeron supplex', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Grindelia stricta ssp. blakei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Layia carnosa', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Phacelia argentea', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Arabis macdonaldiana', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Erysimum franciscanum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Erysimum menziesii', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Thlaspi californicum', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Arctostaphylos nortensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus agnicidus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lathyrus torreyi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Gentiana setigera', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Monardella villosa ssp. globosa', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Castilleja ambigua ssp. humboldtiensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Lilium occidentale', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Viola primulifolia ssp. occidentalis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sidalcea malvaeflora ssp. patula', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Oenothera wolfii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Calystegia atriplicifolia ssp. buttensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cicindela hirticollis gravida', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Scaphinotus behrensi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Scaphinotus longiceps', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Euphydryas editha bayensis', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Euphydryas editha quino', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Speyeria zerene hippolyta', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Oncorhynchus clarkii stomias', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Aletes humilis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Mimulus gemmiparus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Penstemon harringtonii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ephemerella apopsis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pyrgus centaureae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pyrgus ruralis lagunae', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Plecotus rafinesquii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Empidonax fulvifrons', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cnemidophorus burti', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Bufo alvarius', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Rana yavapaiensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Harpagonella palmeri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Castilleja wootonii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Abutilon parishii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Notholaena lemmonii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Graptopetalum bartramii', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Actinemys marmorata', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Rana muscosa', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Rana sierrae', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Batrachoseps regius', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Oncorhynchus mykiss gilberti', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eryngium spinosepalum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Allium tribracteatum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Erigeron multiceps', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Plagiobothrys torreyi var. diffusus', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Arabis bodiensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Epilobium oreganum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pterodroma hasitata', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Pseudemys rubriventris', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Plethodon punctatus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Plethodon shenandoah', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Platanthera leucophaea', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Helenium virginicum', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Liatris helleri', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Arabis serotina', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Paxistima canbyi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cassia fasciculata var. macrosperma', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Isoetes virginica', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pycnanthemum torrei', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Agalinis auriculata', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Helonias bullata', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Smilax pseudochina', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Carex polymorpha', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Scirpus ancistrochaetus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Clematis viticaulis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Prunus alleghaniensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sedum nevii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Canis lupus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Charadrius melodus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Storeria occipitomaculata pahasapae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Cirsium hillii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Asclepias uncialis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Vertigo arthuri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Bison bison athabascae', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Rangifer tarandus groenlandicus', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Chasmistes liorus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Abronia ammophila', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Rhyacophila alexanderi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Oligophlebodes mostbento', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Ovis canadensis sierrae', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Lepus americanus tahoensis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Anaxyrus canorus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Lomatium congdonii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Eriophyllum nubigenum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Trifolium bolanderi', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Mimulus filicaulis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Camissonia sierrae ssp. alticola', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Romneya coulteri', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Gila seminuda', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Lepidomeda mollispinis mollispinis', 'Under Review');
INSERT INTO ConservationStatus VALUES ('Plagopterus argentissimus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Lomatium graveolens var. clarkii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Erigeron canaani', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Sphaeromeria ruthiae', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Jamesia americana var. zionis', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Astragalus ampullarioides', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Astragalus ampullarius', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Pediomelum epipsilum', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Camissonia bairdii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Epilobium nevadense', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Carex haysii', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Trichechus manatus', 'Endangered');
INSERT INTO ConservationStatus VALUES ('Crocodylus acutus', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Caretta caretta', 'Threatened');
INSERT INTO ConservationStatus VALUES ('Falco columbarius', 'Species of Concern');
INSERT INTO ConservationStatus VALUES ('Iris missouriensis', 'Species of Concern');
